src/__init__.py
from dotenv import load_dotenv
from flask import Flask
import os

# Load environmental Variables
load_dotenv()
# Create the flask app
app = Flask(__name__)
# Set the secret key
app.secret_key = os.urandom(24)

# Apply routes from main to the app
from src.main.routes import main
app.register_blueprint(main.main)

src/main/routes/main.py
from flask import Blueprint, request, render_template, redirect,url_for, flash

from joblib import load
import pandas as pd
from math import floor

# Load the machine learning model to memory
data = load("./Models/0004.joblib")
model = data["model"] 


main = Blueprint("main", __name__)

@main.route("/")
def mainRoute():
    '''The main page of the webiste. Displays a form for calculating a transcoding time prediciton.'''
    return render_template("main.html")

@main.route("/predict")
def predictRoute():
    """Route to predict the transcoding time using the machine learning model. 
    Flashes a message with the time prediction and redirects back to the main route"""
    # #######################################################################
    # Sample data in the correct order to pass to the machine learning model
    # #######################################################################
    # data = {'onehotencoder__codec_flv':0,
    #         'onehotencoder__codec_h264':0,
    #         'onehotencoder__codec_mpeg4' :1,
    #         'onehotencoder__codec_vp8':0,
    #         'onehotencoder__o_codec_flv' :0,
    #         'onehotencoder__o_codec_h264':0,
    #         'onehotencoder__o_codec_mpeg4' :1,
    #         'onehotencoder__o_codec_vp8':0,
    #         'remainder__duration' :130.35667,
    #         'remainder__width' :176,
    #         'remainder__height':144,
    #         'remainder__bitrate' :54590,
    #         'remainder__framerate' :12,
    #         'remainder__frames':1564,
    #         'remainder__size' :889537,
    #         'remainder__o_bitrate' :56000,
    #         'remainder__o_framerate':12,
    #         'remainder__o_width':176,
    #         'remainder__o_height':144}
    
    # Check all arguements were provided in the route. 
    for i in request.args:
        if request.args.get(i) == "":
            return redirect(url_for("main.mainRoute"))

    # Init the data object    
    data = {
            'onehotencoder__codec_flv':0,
            'onehotencoder__codec_h264':0,
            'onehotencoder__codec_mpeg4' :0,
            'onehotencoder__codec_vp8':0,
            'onehotencoder__o_codec_flv' :0,
            'onehotencoder__o_codec_h264':0,
            'onehotencoder__o_codec_mpeg4' :0,
            'onehotencoder__o_codec_vp8':0,

            'remainder__duration' :float(request.args.get("duration")),
            'remainder__width' :float(request.args.get("video-width")),
            'remainder__height':float(request.args.get("video-height")),
            'remainder__bitrate' :float(request.args.get("video-bitrate")),
            'remainder__framerate' :float(request.args.get("video-framerate")),
            'remainder__frames': 0,
            'remainder__size' :float(request.args.get("video-size")),
            'remainder__o_bitrate' :float(request.args.get("output-video-bitrate")),
            'remainder__o_framerate':float(request.args.get("output-video-framerate")),
            'remainder__o_width':float(request.args.get("output-video-width")),
            'remainder__o_height':float(request.args.get("output-video-height"))
            }

    # Get the codec values passed in the URL        
    startCodec = request.args.get("codec")
    transcodeCodec = request.args.get("output-codec")
    # Set the start codec value to 1 based on the provided value
    match startCodec:
        case "flv":
            data["onehotencoder__codec_flv"] = 1
        case "h264":
            data["onehotencoder__codec_h264"] = 1
        case "mpeg4":
            data["onehotencoder__codec_mpeg4"] = 1
        case "vp8":
            data["onehotencoder__codec_vp8"] = 1

    # Set the transcode codec value to 1 based on the provided value
    match transcodeCodec:
        case "flv":
            data["onehotencoder__o_codec_flv"] = 1
        case "h264":
            data["onehotencoder__o_codec_h264"] = 1
        case "mpeg4":
            data["onehotencoder__o_codec_mpeg4"] = 1
        case "vp8":
            data["onehotencoder__o_codec_vp8"] = 1

    # Calculate and set the number of frames using the frame rate and duration
    data["remainder__frames"] =  floor(data['remainder__duration'] * data['remainder__framerate'])
    



    # Create the dataframe using the data provided
    df = pd.DataFrame(data,index=[0]) 
    # Flash the prediciton to the user and redirect to main page.    
    flash(f"It should take about {model.predict(df)[0]}seconds to transcode this video!!")
    return redirect(url_for("main.mainRoute"))

@main.route("/Model")
def modelRoute():
    """Route for infomation on the model"""
    return render_template("model.html")

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Computer Science Capstone</title>
    <link rel="stylesheet" href="{{url_for('static', filename='styles.css')}}">
    <link rel="shortcut icon" href="{{url_for('static', filename='favicon.ico')}}" type="image/x-icon">
</head>
<body>
    <nav id="top-nav">
        <a href="{{url_for('main.mainRoute')}}">Home</a>
        <a href="{{url_for('main.modelRoute')}}">Model Information</a>
        <h1 id="site-title">Computer Science Capstone</h1>
    </nav>
    <main>
        {% for message in get_flashed_messages() %}
        <p class='flash_message'>{{ message }}

            <a href="/">Close</a>
        </p>
        {% endfor %}
        {% block content %}{% endblock %}
    </main>
</body>
</html>

src/templates/main.html
{% extends 'base.html' %}
{% block content %}
<div class="prediction-form">
    <h1>prediction-form</h1>
    <form action="{{url_for('main.predictRoute')}}">
        <div class="video-properties">
            <label for="duration-input">Video Duration</label>
            <input type="number" name="duration" id="duration-input">
            <label for="codec">Video Codec</label>
            
            <div class="radios">
            <input type="radio" name="codec" id="codec-input-flv" value="flv">
            <label for="codec-input-flv">FLV</label>
            <input type="radio" name="codec" id="codec-input-h264" value="h264">
            <label for="codec-input-h264">h264</label>
            <input type="radio" name="codec" id="codec-input-mpeg4" value="mpeg4">
            <label for="codec-input-mpeg4">MPEG4</label>
            <input type="radio" name="codec" id="codec-input-vp8" value="vp8">
            <label for="codec-input-vp8">VP8</label>
            </div>

            <label for="video-width-input">Video Width</label>
            <input type="number" name="video-width" id="video-width-input">
            <label for="video-height-input">Video Height</label>
            <input type="number" name="video-height" id="video-height-input">
            <label for="video-bitrate-input">Video Bitrate</label>
            <input type="number" name="video-bitrate" id="video-bitrate-input">
            <label for="video-framerate-input">Video Framerate</label>
            <input type="number" name="video-framerate" id="video-framerate-input">
            <label for="video-size-input">Video Size</label>
            <input type="number" name="video-size" id="video-size-input">

        </div>
        <br>
        <br>
        <div class="transcode-properties">
            <label for="output-codec">Output Video Codec</label>
            
            <div class="radios">
            <input type="radio" name="output-codec" id="output-codec-input-flv" value="flv">
            <label for="output-codec-input-flv">FLV</label>
            <input type="radio" name="output-codec" id="output-codec-input-h264" value="h264">
            <label for="output-codec-input-h264">h264</label>
            <input type="radio" name="output-codec" id="output-codec-input-mpeg4" value="mpeg4">
            <label for="output-codec-input-mpeg4">MPEG4</label>
            <input type="radio" name="output-codec" id="output-codec-input-vp8" value="vp8">
            <label for="output-codec-input-vp8">VP8</label>
            </div>

            <label for="output-video-width-input">Output Video Width</label>
            <input type="number" name="output-video-width" id="output-video-width-input">
            <label for="output-video-height-input">Output Video Height</label>
            <input type="number" name="output-video-height" id="output-video-height-input">
            <label for="output-video-bitrate-input">Output Video Bitrate</label>
            <input type="number" name="output-video-bitrate" id="output-video-bitrate-input">
            <label for="output-video-framerate-input">Output Video Framerate</label>
            <input type="number" name="output-video-framerate" id="output-video-framerate-input">


        </div>
        <button type="submit">Submit</button>
    </form>
</div>



{% endblock %}

src/templates/model.html
{% extends 'base.html' %}
{% block content %}
<h1>Decision Tree Regression</h1>
The algorithm used for the prediciton of the transcoding times for this project was decison tree regression.
The algorithm was trained on a dataset of roughly 16000 entries 
collected from the University of California Irvine Machinie Learning Repository. The model has an r^2 score of 0.9813526253175591. 
Below are some figures depicting elements of the mode

<div>
    <h2>Prediction Error</h2>
    <img src="{{url_for('static', filename='0004DecisionTreePredictionErrorDisplay.png')}}" >
</div>
<div>
    <h2>Partial Dependencies</h2>
    <img src="{{url_for('static', filename='0004DecisionTreePartialDependencies.png')}}" >
</div>
<div>
    <h2>First 3 Levels of Tree Model</h2>
    <img src="{{url_for('static', filename='TreeModelFirst3.png')}}" >
</div>
<div>
    <h2>Full Tree Model</h2>
    <img src="{{url_for('static', filename='TreeModel.png')}}" >
</div>



{% endblock %}